### ISSUE TITLE
`Workflow.roots()` bug with non-function task

### ISSUE THREAD

**Issue by multimeric** [haesleinhuepf/napari-workflows#41]
Here is an example:
```python
from napari_workflows import Workflow

w = Workflow()
w.set("x", 10)
w.roots()
```
```
Traceback (most recent call last):
  File "/Users/milton.m/Programming/workflows_bug.py", line 5, in <module>
    w.roots()
  File "/opt/anaconda3/envs/napari2/lib/python3.10/site-packages/napari_workflows/_workflow.py", line 112, in roots
    keys_with_functions = [key for key, task in self._tasks.items() if callable(task[0])]
  File "/opt/anaconda3/envs/napari2/lib/python3.10/site-packages/napari_workflows/_workflow.py", line 112, in <listcomp>
    keys_with_functions = [key for key, task in self._tasks.items() if callable(task[0])]
TypeError: 'int' object is not subscriptable
```

Using `napari-workflows==0.2.9`.

Should be an easy fix.

**Comment by multimeric** [comment]
Actually this happens in a few other places too, including `.followers_of()` and therefore `.leafs()`.

**Comment by haesleinhuepf** [comment]
Hi @multimeric ,

good catch! This should be easily fixable, indeed.

Best,
Robert
