### ISSUE TITLE
`None` arguments

### ISSUE THREAD

**Issue by multimeric** [haesleinhuepf/napari-workflows#43]
`None` arguments are removed from the argument list which I don't think is desirable. The logic here also throws an `IndexError`:
```python
from napari_workflows import Workflow

def identity(x):
    return x

w = Workflow()
w.set("x", identity, None)
```

```
Traceback (most recent call last):
  File "/Users/milton.m/Programming/workflows_bug.py", line 7, in <module>
    w.set("x", identity, None)
  File "/opt/anaconda3/envs/napari2/lib/python3.10/site-packages/napari_workflows/_workflow.py", line 57, in set
    while (used_args[-1] is None):
IndexError: list index out of range
```

**Comment by haesleinhuepf** [comment]
Hi @multimeric ,

can you tell me something about your use-case where this is a problem?

Besr,
Robert

**Comment by multimeric** [comment]
I have an incomplete user-defined workflow `w`, and then I want to add some extra steps and data to that workflow. Some of my metadata just happens to be `None`: that is the real value that I want to be in the workflow.

**Comment by haesleinhuepf** [comment]
Would be using dask graphs instead of napari workflows an option?
https://docs.dask.org/en/stable/graphs.html

As far as I know there is no napari-plugin where "None" parameters are supported. Thats why this never popped up as a problem. Are you using napari and napari-assistant to setup your workflow?

**Comment by multimeric** [comment]
Well, I think the intention is that the user defined workflow might be created using `napari-assistant`, and indeed that probably won't have `None`. But the issue is that the metadata I subsequently want to add to the workflow could include `None`. 

I think it should be possible to solve by using a different placeholder value other than `None` in the previous step:
https://github.com/haesleinhuepf/napari-workflows/blob/d57be7573cbf0044c0882a92dc303d34157d22e3/src/napari_workflows/_workflow.py#L52-L54

And then removing that placeholder from the end, instead of removing `None`:
https://github.com/haesleinhuepf/napari-workflows/blob/d57be7573cbf0044c0882a92dc303d34157d22e3/src/napari_workflows/_workflow.py#L56-L58

**Comment by haesleinhuepf** [comment]
Ok, that sounds like a plan. Would you have the time to implement this and test it? For example a custom object could be a suitable placeholder. If you find it working with the assistant, please send a pull-request. I would then test it more and merge it if it looks ok. Let's just keep in mind that napari-workflows is downloaded 1000 times per week. Hence modifications must be done carefully to prevent breaking things.

One alternative though: It seems None parameters are only removed from the end of parameter lists. Hence, if you add None as default values to the parameters of your functions, it should just work.

Thanks for the proposal!
